mask password in config
invitae/kafka-connect-rabbitmq pull request #3
Opened 2019-05-02 17:25 UTC by unthingable

2019-05-02 17:28 UTC, ashinohara approved these changes

2019-05-06 23:54 UTC, ashinohara requested changes
I think we need to change line #86 as well:

`this.password = this.getString(PASSWORD_CONFIG);`

I am getting the following exception in test env:

```
java.lang.ClassCastException: org.apache.kafka.common.config.types.Password cannot be cast to java.lang.String
	at org.apache.kafka.common.config.AbstractConfig.getString(AbstractConfig.java:126)
	at com.github.jcustenborder.kafka.connect.rabbitmq.RabbitMQConnectorConfig.<init>(RabbitMQConnectorConfig.java:86)
	at com.github.jcustenborder.kafka.connect.rabbitmq.RabbitMQSourceConnectorConfig.<init>(RabbitMQSourceConnectorConfig.java:48)
	at com.github.jcustenborder.kafka.connect.rabbitmq.RabbitMQSourceTask.start(RabbitMQSourceTask.java:52)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

2019-05-07 15:11 UTC, ashinohara approved these changes

2021-06-10 21:32 UTC, closed without merging

2021-06-10 22:02 UTC, unthingable commented
:(